language: node_js
node_js:
- '6'
notifications:
  slack:
    secure: MJPx0wyUVHxEZI4wzfNYXyliAZJNZOqaXTUWkSAD3efVqVFQgetIGnGuhC9A08c0vZI8OFyn1lciuZ3IejQaUg3cJZU/H12CMfItxEFQmjduX++wSOFCYXL3RWi8nEBWSeq6HviWoAmRJ8rmfyRpLxeASQ8E8nGv6csHSPnMietKRBH4JvXjqCTg37lTJmIqG6A6Fxvq2XpPusJT9YYofIfS0CKTNwfaNvZ/+PD4rcgWC4VSDuJ8bxWKiIwH3Ka7Xd/6uaZHAAq28ZsybXE0x3E++SK4dy18c/cUsBgzmYfZBGk1/bw6DFdIYKe2iQRBCF4yEB1iKT23GR+gZkjsJd1jREm1p4jUFh9dli/kftl1oaDQzDOt1ZAoUcpRcT5jZcXAR9CTV/xq0DevCwl1CA7t4Jz2Z6y9FZrjrKToxtjdetozZwQQFqsvcVl1lnGyVjHSQgAuiozCaBlIpPzcjtUdl4kJAMCIfCrtLSvv46iEc1t2ImrIbSCt7QIvjXRd7kU9+NJS9u3NyIHH14TkD507VliggDqn0CtndZImRp1id6w9Ba+bQg13qG1vKMr8W0D5ZH81aVIaxjkm6m3HlIOU1U7Efu2mJtLOu47UPBIk/U4nV6OifETXbVBSDqfLFcmZGX+zxIu3xIdmy0m1mFCe4Z8Tf3s8lXNha5ssQ5Y=
